// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by generate_assets.dart

class GeneratedAssets {
  // static final List<String> minecraftFiles = <String>[
  //   'images/minecraft/steve.png',
  //   'images/minecraft/alex.png',
  //   'images/minecraft/tnt.png',
  //   'images/minecraft/zombie.png',
  //   'images/minecraft/zombie-chicken.png',
  //   'images/minecraft/skeleton.png',
  //   'images/minecraft/pig.png',
  // ];

  // static final List<String> amongusFiles = <String>[
  //   'images/among_us/lime.png',
  //   'images/among_us/yellow.png',
  //   'images/among_us/blue.png',
  //   'images/among_us/black.png',
  //   'images/among_us/orange.png',
  //   'images/among_us/cyan.png',
  //   'images/among_us/grey_blue.png',
  //   'images/among_us/brown.png',
  //   'images/among_us/magenta.png',
  //   'images/among_us/impostor.png',
  //   'images/among_us/red.png',
  //   'images/among_us/purple.png',
  // ];

  static final List<String> minecraftFiles = <String>[
    'images/minecraft/steve.png',
    'images/minecraft/alex.png',
    'images/minecraft/pig.png',
    'images/minecraft/zombie.png',
  ];

  static final List<String> amongusFiles = <String>[
    'images/among_us/lime.png',
    'images/among_us/yellow.png',
    'images/among_us/blue.png',
    'images/among_us/impostor.png',
    'images/among_us/purple.png',
  ];

  static final List<String> minecraft_2Files = <String>[
    'images/minecraft/steve.png',
    'images/minecraft/alex.png',
  ];

  static Map<String, List<String>> get allLists => {
        'minecraft': minecraftFiles,
        'amongus': amongusFiles,
        'minecraft_2': minecraft_2Files,
      };
}
