name: Deploy Flutter Web App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter pub get
    - run: flutter build web
    - uses: bluefireteam/flutter-gh-pages@v8
      with:
        webRenderer: canvaskit
